#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &localRepo "http://localhost/local/default.git"

strains:
  - name: default
    url: http://localhost:3000/
    code: *localRepo
    content: *localRepo
    static: *localRepo