#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "ssh://git@github.com/adobe/helix-example-advanced.git"

strains:
  - name: default
    code: ssh://git@github.com/adobe/helix-example-advanced.git#master
    content: ssh://git@github.com/adobe/helix-example-advanced.git#master
    static: ssh://git@github.com/adobe/helix-example-advanced.git/htdocs#master
    package: bdelacre/d6bfeced75e009dd89c40596e4bda46f0e257088
