#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "ssh://git@github.com/adobe/helix-example-advanced.git"

strains:
  - name: default
    code: ssh://git@github.com/adobe/helix-example-advanced.git#master
    content: ssh://git@github.com/adobe/helix-example-advanced.git#master
    static: ssh://git@github.com/adobe/helix-example-advanced.git/htdocs#master
    package: bdelacre/0c457f711c3dfcfd29548599a1eff82cfe4fd73c
